### ISSUE TITLE
cron

### ISSUE THREAD

**Issue by Eduu84** [vaudois/yiimp_install_scrypt#11]
During the installation of daemon coin, there is a failure with cron:

` FINISH! Updating New Cron for adding MEM if necesary
 File SCREENS not exist creating... load from /tmp/tmp.X2xRArDgNy/utils
 Done.

 to start crons shell command:  mem restart AND screens stratum restart
 File MEM.SH & MEM.PHP not exist copy from /tmp/tmp.X2xRArDgNy/utils to /var/web/crons/***
sed: can't read /var/web/crons/mem.sh: No such file or directory
 File STRATDAEM.SH & STRATDAEM.PHP not exist copy from /tmp/tmp.X2xRArDgNy/utils to /var/web/crons/***
sed: can't read /var/web/crons/stratdaem.sh: No such file or directory
./start: line 834: /var/web/crons/stratdaem.sh: No such file or directory
 FINISSED!!!!!`

[Sin título](https://github.com/vaudois/yiimp_install_scrypt/assets/101891578/e552d199-8f6e-4da2-8d52-4933feaa3d07)

**Comment by vaudois** [comment]
MEM.php and stratdaem.php is from beta from other options
without this run normal your pool not problem
close this
