### ISSUE TITLE
Wrong Block Reward Amount

### ISSUE THREAD

**Issue by vanc79** [vaudois/yiimp_install_scrypt#12]
I have almost every thing working correctly. The block reward value is wrong, but I am getting the correct reward amount when block found. The value is 24.414 LCC under Amount, it should be 15.625 LCC. Some help to point me in the right direction would be much appreciated. 
![Screenshot 2024-03-12 075026](https://github.com/vaudois/yiimp_install_scrypt/assets/163137516/6022a768-6872-445a-ad93-362fb77e3e79)

**Comment by vaudois** [comment]
hello this problem adjust block reward en admin panel on SETTINGS Reward Mul....
this question is not from my install is from Yiimp.... use Discord to wrhite yous questions from Yiimp
clise this

**Comment by vanc79** [comment]
This problem is in LCC wallet RPC. you have done a great job making an installer. I have contacted LCC developers about this issue. Its a php issue.
