### ISSUE TITLE
Script finished without issues - but nothing showing on the web server

### ISSUE THREAD

**Issue by yanir99** [vaudois/yiimp_install_scrypt#13]
Everything ran and finished ok - but when opening the server URLs all pages are empty (blank) only one that actually works is the phpmyadmin.
Also the coinbuild exit with errors:
```
cannot open tty-output
menu: menu: cannot execute binary file
./menu: line 31: [: =: unary operator expected
./menu: line 37: [: =: unary operator expected
./menu: line 43: [: =: unary operator expected
./menu: line 49: [: =: unary operator expected
./menu: line 55: [: =: unary operator expected
```

**Comment by vaudois** [comment]
Me installed with out not problems and run good... Selected menu number?

**Comment by yanir99** [comment]
Hi I installed it on a clean Ubuntu 20.04 Server and selected 4 during the installation.
For the coinbuilder, I get the first message when running the command and when hitting OK to continue it crush with the above messages.

**Comment by vaudois** [comment]
Hello, I'm sorry, I don't understand when you say that when you give it ok it will crush ...

**Comment by Shaggy0815** [comment]
I have the same. Fresh installed ubuntu 20.04 server. 
The installation went ok.
Reboot done.
if you start coinbuild it starts with Demon installer.
And a warning that the installer is only for Yiimp!
Then if you press "ok" it will crash with the following output:
cannot open tty-output
menu: menu: cannot execute binary file
./menu: line 31: [: =: unary operator expected                         ┌────────────── Daemon Installer ────────────────┐
./menu: line 37: [: =: unary operator expected                         │ Warning! This Scrypt only works with servers   │  
./menu: line 43: [: =: unary operator expected                         │ setup with the Yiimp!                          │  
./menu: line 49: [: =: unary operator expected                         │                                                │  
./menu: line 55: [: =: unary operator expected
