### ISSUE TITLE
API Problem

### ISSUE THREAD

**Issue by xyrox54** [vaudois/yiimp_install_scrypt#5]
Hello, 

I am developing a UI using the pool API but I realize that the info given by the API is wrong. 
For example it returns me 0 in hashrate on a pool where I have 1.2kh.

Do you know how to fix the problem?

**Comment by vaudois** [comment]
yiimp?,
fijate en current_results.php como recoge la información del hash
linea donde pone -> select hashrate from hashrate where algo=:algo order by time desc limit 1
