### ISSUE TITLE
Error Creating Coin

### ISSUE THREAD

**Issue by minershaven** [vaudois/yiimp_install_scrypt#6]
i can go into the wallets tab and enter all rhe info into it but when i hit create and then try to go back to get the coinconfig out of there  i get this error

![image](https://github.com/vaudois/yiimp_install_scrypt/assets/57435138/98e72efb-a163-44d0-a01e-871c08b138a9)

**Comment by vaudois** [comment]
That doesn't tell me how you tried to create your coin or the config you put... it could be many things

**Comment by minershaven** [comment]
That's just from using the create coin in the pool admin page. After I create it that's what happens when you click on the coin under wallets

**Comment by vaudois** [comment]
It's a yiimp problem, it's not a mi install problem,
the creator of that yiimp should correct it
Thank goodness I already went through that, there are several things in coin_form.php rpchost is empty you will have to put an if if empty replace it with localhost,
The second is the rpcenconding same problem if empty put POW
and I should go...
