### ISSUE TITLE
Commands not found

### ISSUE THREAD

**Issue by andy1986-sudo** [vaudois/yiimp_install_scrypt#8]
Stdout stdin and stderr commands not found trying to install

**Comment by vaudois** [comment]
wath your problem and installed number?

**Comment by andy1986-sudo** [comment]
I have pool installed now but if I try to install again on another server I still get the same errors I've used number 3 selected each time only way I found round it was to use another installer then stop it and use yours for installing yiimp

**Comment by Canefis** [comment]
What yiimp ver shoud I choose for ubunto 20.04. When I grabbed by default "4" it was installed a desktop version on the server, lol :). Should I choose 1 (firefox2014 repo)?

**Comment by Simkas45** [comment]
/etc/functions.sh: line 84: dialog: command not found

**Comment by vaudois** [comment]
hello everyone,
I'm going to try the installer in virtual, it's possible that the yiimp creators of the menus have changed things, I'm going to see what I have to do and correct problems...

**Comment by vaudois** [comment]
hello installed with out errors

**Comment by vaudois** [comment]
![2024-01-06 (5)](https://github.com/vaudois/yiimp_install_scrypt/assets/28846568/6d22fece-26c2-40e9-9bd3-5feb19c913be)
![2024-01-06 (6)](https://github.com/vaudois/yiimp_install_scrypt/assets/28846568/5ede3478-0116-44e7-8f87-51313cc9d83c)
![2024-01-07 (2)](https://github.com/vaudois/yiimp_install_scrypt/assets/28846568/55ce8df6-0dd5-4fef-b25d-4e30272528a8)
![Capture web_7-1-2024_2024_192 168 1 177](https://github.com/vaudois/yiimp_install_scrypt/assets/28846568/24d86441-c743-406c-8165-06cdcf9f50e7)

**Comment by andy1986-sudo** [comment]
Thankyou friend
